language: android
sudo: false
android:
  components:
    - tools
    - build-tools-26.0.2
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support

    # The SDK version used to compile your project
    - android-16
    - android-21
    - android-22
    - android-25
    - android-26

jdk: oraclejdk8
os:
  - linux
