language: android
sudo: false
env:
  global:
    # wait up to 20 minutes for adb to connect to emulator
    - ADB_INSTALL_TIMEOUT=20
android:
  components:
    - tools
    - build-tools-26.0.2
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support

    # The SDK version used to compile your project
    - android-16
    - android-21
    - android-22
    - android-25
    - android-26
  # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-16
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-25
  before_script:
    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

jdk: oraclejdk8
os:
  - linux
